server.port=${PORT:8080}

# ===============================
# MONGODB DATABASE CONFIGURATION
# ===============================
spring.data.mongodb.uri=${MONGODB_URI}

# ===============================
# CLOUDINARY STORAGE CONFIGURATION
# ===============================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ===============================
# JWT & SECURITY
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB